export const AADHAR_IDS = [
  "2345 6789 0123",
  "3456 7890 1234",
  "4567 8901 2345",
  "5678 9012 3456",
  "6789 0123 4567",
  "7890 1234 5678",
  "8901 2345 6789",
  "9012 3456 7890",
  "1234 5678 9012",
  "2468 1357 9024",
];

export const PTYPES = [
  { id: "pothole", label: "Pothole", icon: "" },
  { id: "sewage", label: "Open Sewage", icon: "" },
  { id: "garbage", label: "Garbage Dump", icon: "" },
  { id: "streetlight", label: "Street Light", icon: "" },
  { id: "waterlog", label: "Waterlogging", icon: "" },
];

export const MINS = {
  pothole: {
    name: "Ministry of Road Transport & Highways",
    dept: "MoRTH",
    icon: "",
    bg: "#FFF7ED",
    ac: "#C2410C",
  },
  sewage: {
    name: "Ministry of Jal Shakti",
    dept: "Water & Sanitation",
    icon: "",
    bg: "#EFF6FF",
    ac: "#1D4ED8",
  },
  garbage: {
    name: "Ministry of Housing & Urban Affairs",
    dept: "MoHUA",
    icon: "",
    bg: "#F0FDF4",
    ac: "#15803D",
  },
  streetlight: {
    name: "Ministry of Power",
    dept: "Electricity",
    icon: "",
    bg: "#FAF5FF",
    ac: "#7C3AED",
  },
  waterlog: {
    name: "Ministry of Jal Shakti",
    dept: "Water & Sanitation",
    icon: "",
    bg: "#EFF6FF",
    ac: "#1D4ED8",
  },
};

export const STAGES = [
  { name: "Reported", desc: "Complaint submitted through the portal" },
  { name: "Under Review", desc: "Local officer is reviewing the complaint" },
  { name: "Verified On-Site", desc: "Field inspector confirmed the issue at location" },
  { name: "Department Notified", desc: "Assigned department received the case" },
  { name: "Work Order Issued", desc: "Department raised a work order for repair" },
  { name: "Repair In Progress", desc: "Repair crew has been assigned or deployed" },
  { name: "Resolved", desc: "Issue fixed and case closed" },
];

export const SEED_ISSUES = [
  {
    id: "ISS001",
    type: "pothole",
    title: "Massive pothole on NH-48 near Gurugram Toll",
    desc: "A 3 x 2 ft pothole near the toll plaza. Four tyre bursts were reported this week. Dangerous at night because no warning signs are present.",
    loc: "NH-48, Gurugram, Haryana",
    votes: 24,
    stage: 5,
    by: "9012 3456 7890",
    date: "2026-02-20",
    photo: null,
    voters: ["9012 3456 7890"],
    stageDates: [18, 16, 14, 12, 9, 3, null],
  },
  {
    id: "ISS002",
    type: "sewage",
    title: "Open sewage overflow on Ring Road",
    desc: "Cracked pipeline with raw sewage on the footpath for six days. Residents report severe odour and skin infection risk.",
    loc: "Ring Road, New Delhi",
    votes: 19,
    stage: 3,
    by: "3456 7890 1234",
    date: "2026-02-28",
    photo: null,
    voters: ["3456 7890 1234"],
    stageDates: [5, 4, 3, 1, null, null, null],
  },
  {
    id: "ISS003",
    type: "garbage",
    title: "Illegal garbage dump near Kendriya Vidyalaya",
    desc: "Large garbage heap near the primary school gate. Children walk past waste every morning and residents report rodents daily.",
    loc: "Sector 15, Noida, UP",
    votes: 13,
    stage: 2,
    by: "4567 8901 2345",
    date: "2026-03-01",
    photo: null,
    voters: ["4567 8901 2345"],
    stageDates: [4, 2, 1, null, null, null, null],
  },
  {
    id: "ISS004",
    type: "streetlight",
    title: "All street lights out on MG Road 500m stretch",
    desc: "Street lights have been dark for two weeks. Residents reported three accidents and safety concerns after dark.",
    loc: "MG Road, Bengaluru",
    votes: 9,
    stage: 1,
    by: "5678 9012 3456",
    date: "2026-03-03",
    photo: null,
    voters: ["5678 9012 3456"],
    stageDates: [2, 1, null, null, null, null, null],
  },
  {
    id: "ISS005",
    type: "waterlog",
    title: "Chronic waterlogging blocks residential lane",
    desc: "Standing water has remained for more than four days after rain. Lane is difficult to cross and mosquito breeding risk is rising.",
    loc: "Salt Lake, Kolkata",
    votes: 6,
    stage: 0,
    by: "6789 0123 4567",
    date: "2026-03-04",
    photo: null,
    voters: ["6789 0123 4567"],
    stageDates: [1, null, null, null, null, null, null],
  },
];
